services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    volumes:
      - ./docker/nginx-proxy/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - ${NGINX_PROXY_HTTP_PORT:-80}:80
      - ${NGINX_PROXY_HTTPS_PORT:-443}:443
    networks:
      - anzusystems_network

networks:
  anzusystems_network:
    external: true
