services:
  app:
    build:
      args:
        - DOCKER_USER=${DOCKER_USER:-user}
        - DOCKER_USER_ID=${DOCKER_USER_ID:-1000}
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:-1000}
      context: .
      dockerfile: docker/app/local/Dockerfile
    environment:
      - VIRTUAL_HOST=notification-server.anzusystems.local
      - VIRTUAL_PORT=8080
    env_file:
      - .env.docker.dist
      - .env.docker.local
    volumes:
      - ".:/var/www/html:cached"
    ports:
      - ${NGINX_PORT:-8490}:8080
      - ${NGINX_UPSTREAM_WEBSOCKET_PORT:-3410}:3005
    hostname: notification-server.anzusystems.local
    networks:
      anzusystems_network:
        aliases:
          - notification-server

networks:
  anzusystems_network:
    external: true
